services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"